#!/bin/bash

if [ -z $GITHUB_ACCESS_TOKEN ]; then
    echo "Missing Environment Variable: GITHUB_ACCESS_TOKEN"
    exit 1
fi

if [ -z $1 ]; then
    echo "Usage:"
    echo "cloneall <github_org>"
    exit 1
fi

ORG=$1

OUTPUT=$(curl \
  --silent \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $GITHUB_ACCESS_TOKEN"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/orgs/$ORG/repos)

echo $OUTPUT | jq --raw-output ".[].name" | while read repo; do
    echo "Cloning repo: $repo"
    git clone git@github.com:${ORG}/${repo}.git
done
